version: "3.9"

services:
  imgpedia_backend:
    build: .
    image: elemma00/imgpedia_backend:latest
    restart: unless-stopped
    environment:
      - TDB_PATH=/imgpedia_tdb
    volumes:
      - /home/efaundez/imgpedia_backend/rdfs:/rdfs
      - /NAS/sferrada/imgpedia/imgpedia_tdb:/imgpedia_tdb
      - /NAS/sferrada:/nas_mount
      - /NAS/sferrada/imgpedia/resource:/nas_mount/imgpedia/resource
    ports:
      - "8081:8081"
    user: "${UID:-1000}:${GID:-1000}"