spring.application.name=imgpedia_backend
server.port=8081

springdoc.api-docs.enabled=true

# Configuring size for file uploads
spring.servlet.multipart.max-file-size=500GB
spring.servlet.multipart.max-request-size=500GB

# Configuration for H2 database (for development purposes)
spring.datasource.url=jdbc:h2:file:${user.dir}/imgpedia_users;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=emma
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

admin=admin
password=admin
# JPA configuration
spring.jpa.hibernate.ddl-auto=update

# JWT configuration
jwt.secret=imgpediaSecretKeyMustBeAtLeast32CharactersLong
jwt.expiration=86400000


server.tomcat.max-swallow-size=-1
spring.mvc.async.request-timeout=-1

logging.level.org.springframework.web=INFO
logging.level.com.imgpedia.imgpedia_backend=INFO

# Configuring logging for the application
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=/app/logs
logging.file.name=${logging.file.path}/imgpedia_backend.log
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/imgpedia_backend.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
logging.logback.rollingpolicy.clean-history-on-start=false