spring.application.name=imgpedia_backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.web=INFO
logging.level.com.imgpedia.imgpedia_backend=INFO

# Configurar el formato del log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n